### PR TITLE
fix bug about getShrinkRatio

### PR DESCRIPTION
**Pull request by why520crazy**
we found a bug when set maxWidth and maxHeight are 200px，fix bug about upload an image what width is 150px and height is 300px

### CODE REVIEW

**Comment by zhenshuaiwws** [comment]
```
ngJcropConfigProvider.setJcropConfig({ maxHeight:300

$scope.getShrinkRatio = function(){
  var img = $('<img>').attr('src', $scope.mainImg[0].src)[0];
  if(ngJcropConfig.jcrop.maxWidth > img.width || ngJcropConfig.jcrop.maxHeight > img.height){

```
When the image is size 200*400, the last line judgement is true, but the image will be compressed,  lead to computational error.
So we discovery it, and modify judgement as and.

**Comment by andrefarzat** [comment]
I could not understand the problem and the solution you guys have.
I added a [200x400 image to the demo](https://github.com/andrefarzat/ng-jcrop/commit/38bcd94319375ad5ae0dd7cc3c54a302f0d1547a). Please, edit it to replicate the problems you guys have.

Thanks a lot

**Comment by zhenshuaiwws** [comment]
No, you misunderstand it.
Your demo looks no problem, but you are wrong.
Because the end result is selection, not coords, so the preview is right, but the final result is wrong, because the shrinkRatio value is wrong.
```
            $scope.coords[0] = coords.x;
            $scope.coords[1] = coords.y;
            $scope.coords[2] = coords.x2;
            $scope.coords[3] = coords.y2;
            $scope.coords[4] = coords.w;
            $scope.coords[5] = coords.h;

            var shrinkRatio = $scope.getShrinkRatio();
            $scope.selection[0] = Math.round(coords.x * shrinkRatio);
            $scope.selection[1] = Math.round(coords.y * shrinkRatio);
            $scope.selection[2] = Math.round(coords.x2 * shrinkRatio);
            $scope.selection[3] = Math.round(coords.y2 * shrinkRatio);
            $scope.selection[4] = Math.round(coords.w * shrinkRatio);
            $scope.selection[5] = Math.round(coords.h * shrinkRatio);
```

**Comment by why520crazy** [comment]
You can select the same area under you set maxWidth=300 maxHeight=300 and maxWidth=600 maxHeight=600,We should expect the same selection，but the result are not same.

**Comment by andrefarzat** [comment]
@zhenshuaiwws, @why520crazy,
I think I understood what you guys meant. But I believe that the or operator (`||`) is the correct on, for if the image is less than `maxWidth` or less than `maxHeight`, it will be reduce in both width and height. So the preview is showing related to the image which is being displayed.

So, the calculus to crop the image in the backend side should be aware to reduce or increase the image size ( or the selection array ) to crop it. The information which is really missing to be given to backend is the width and height of the displayed image. Here the official (legacy) doc about how to crop in the backend: http://legacy.jcrop.org/content/Jcrop_Implementation_Theory.html

I was planning do a task force to migrate this to make it work with the jCrop 2.0. May I ask what jCrop you guys are using ?

**Comment by why520crazy** [comment]
thinks, we are using jCrop 0.9.12.

**Comment by naneri** [comment]
" But I believe that the or operator (||) is the correct one, for if the image is less than maxWidth or less than maxHeight, it will be reduce in both width and height. So the preview is showing related to the image which is being displayed." 

It should not be || because if an image is smaller by at least one axis - it will aready be shrinked by that axis. So 1 should only be returned if image is smaller by both axis.

**Comment by andrefarzat** [comment]
@naneri That was the original point. If the image is bigger in any of the axes, it should shrink to fit in the area and keep its ratio for future cropping

**Comment by naneri** [comment]
@andrefarzat But the code logic is so, that the image is getting shrinked, but the shrink ratio still is 1, though it should use the shrink ratio of the axis that was larger than the limit of HTML element.

**Comment by andrefarzat** [comment]
Version 2.1.2 launched. Thank you, guys :smile_cat:

**Comment by naneri** [comment]
@andrefarzat Ok, great

**Pull request merged**
