### PR TITLE
add thumbnail-wrapper-selector has a new optionnal ng-jcrop parameters

### PR DESCRIPTION
**Pull request by vergerf**
Hi,
I've add a new feature to the project which allow the user to uses thumbnail somewhere else in the page.
I thought you might be interested to merge it to the master branch.

### CODE REVIEW

**Comment by andrefarzat** [comment]
That 's a good addition. May I ask you to write a test for it?

**Comment by vergerf** [comment]
Hi,
I Found a bug on big images (like 1920x1080). 
you use:
```
$('<img>').attr('src', $scope.mainImg[0].src)[0]);
```
but the image doesn't have enough time to be loaded. So I used the onload to fixed it.

I did the same for the thumbnail in getShrinkRatio() where you recreate an virtual  tag to get width and height. I put it in the scope in the onMainImageLoad function.

But now, some tests doesn't pass because the onMainImageLoad isn't called (onload is not called yet). Should I put my changes in the initMainImage function? Or change the tests to make them take caution of the time needed to be loaded.

**Comment by andrefarzat** [comment]
@vergerf Sorry take this long time to return here. I gonna study your changes to understand better

**Comment by andrefarzat** [comment]
@vergerf I've found it weird, for there is a test for a 3888x2592 image (yep, exaggerated in propose) before. I've seen you're using `document` which doesn't [make angular happy](https://docs.angularjs.org/api/ng/service/$document).

I think we can simplify the code adding the `thumbnailWrapperSelector` property and giving it the default value `".ng-jcrop-thumbnail"`. So, we inject the code to create the thumbnail in the div. What do you think ?

**Pull request closed without merging**
